/**
 * ReportsPage.tsx — Smart Reports and Decision Center
 * - Executive Summary generated by AI based on live platform data
 * - Leadership Status: hierarchical layout — most important first — reading time ≤30 seconds
 * - Interactive AI assistant responding based on platform readings and actual data
 * - Real CSV/JSON export
 * - 14-day analytical charts
 */
import { useState, useMemo, useRef, useEffect } from 'react';
import {
  AreaChart, Area, BarChart, Bar, LineChart, Line,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend,
  ReferenceLine
} from 'recharts';
import {
  BarChart3, Download, FileText, TrendingUp, Calendar,
  FileDown, Brain, Send, RefreshCw, AlertTriangle,
  CheckCircle, Zap, MessageSquare, Sparkles, ChevronDown, ChevronUp,
  User, Bot, Loader2, Copy, Check, Eye, EyeOff, Crown, Shield,
  Activity as ActivityIcon, Target, Clock, MapPin
} from 'lucide-react';
import { toast } from 'sonner';
import { floodRiskTrend, systemStats } from '@/data/mockData';
import { useRealWeather, computeWeatherSummary } from '@/hooks/useRealWeather';
import { trpc } from '@/lib/trpc';
import InfoTooltip, { type TooltipContent } from '@/components/InfoTooltip';
import { Streamdown } from 'streamdown';
import KPIDrillDown, { type DrillDownType } from '@/components/KPIDrillDown';
import RegionDetailModal from '@/components/RegionDetailModal';
import { useLanguage } from '@/contexts/LanguageContext';

// ─── Design tokens ────────────────────────────────────────────────────────────
const T = {
  bg:        '#0D1B2A',
  card:      'rgba(21,34,51,0.90)',
  cardHov:   'rgba(28,44,64,0.95)',
  border:    'rgba(66,165,245,0.12)',
  borderAct: 'rgba(66,165,245,0.35)',
  blue:      '#42A5F5',
  teal:      '#4DD0E1',
  green:     '#43A047',
  amber:     '#FFB300',
  red:       '#FF6B35',
  purple:    '#AB47BC',
  text:      '#E8F4F8',
  textSub:   '#90CAF9',
  textMuted: '#546E7A',
  fontHead:  'Playfair Display, Georgia, serif',
  fontMono:  'Space Mono, Courier New, monospace',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
function gen14DayRainfall() {
  const now = new Date();
  return Array.from({ length: 15 }, (_, i) => {
    const d = i - 7;
    const date = new Date(now);
    date.setDate(date.getDate() + d);
    const label = d === 0 ? 'Today' : d < 0 ? `${Math.abs(d)}m` : `+${d}m`;
    const base = Math.max(0, Math.sin((d + 5) * 0.7) * 3.5 + Math.random() * 2);
    return {
      time: label,
      date: date.toLocaleDateString('ar-AE', { month: 'short', day: 'numeric' }),
      actual: d > 0 ? null : +base.toFixed(2),
      predicted: +(base * (d > 0 ? 1.2 : 0.9) + Math.random() * 1.5).toFixed(2),
      isCurrent: d === 0,
    };
  });
}

function gen14DayRiskTrend() {
  const now = new Date();
  return Array.from({ length: 15 }, (_, i) => {
    const d = i - 7;
    const date = new Date(now);
    date.setDate(date.getDate() + d);
    const label = d === 0 ? 'Today' : d < 0
      ? date.toLocaleDateString('ar-AE', { month: 'short', day: 'numeric' })
      : `+${d}m`;
    const t = (d + 7) / 14;
    return {
      date: label,
      isCurrent: d === 0,
      abuDhabiCity: Math.max(5, Math.round(20 + Math.sin(t * Math.PI * 2) * 15 + Math.random() * 8)),
      alAin:        Math.max(5, Math.round(45 + Math.sin(t * Math.PI * 2 + 1) * 20 + Math.random() * 10)),
      alDhafra:     Math.max(5, Math.round(30 + Math.sin(t * Math.PI * 2 + 2) * 12 + Math.random() * 6)),
      alWathba:     Math.max(5, Math.round(60 + Math.sin(t * Math.PI * 2 + 3) * 25 + Math.random() * 12)),
    };
  });
}

function downloadCSV(filename: string, rows: Record<string, unknown>[]) {
  if (!rows.length) return;
  const headers = Object.keys(rows[0]);
  const csv = [headers.join(','), ...rows.map(r =>
    headers.map(h => { const v = r[h]; const s = v == null ? '' : String(v); return s.includes(',') || s.includes('"') ? `"${s.replace(/"/g, '""')}"` : s; }).join(',')
  )].join('\n');
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' }));
  a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
}

function downloadJSON(filename: string, data: unknown) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }));
  a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
}

// ─── Risk badge ───────────────────────────────────────────────────────────────
function RiskBadge({ level, score }: { level: string; score: number }) {
  const colors: Record<string, { bg: string; border: string; text: string }> = {
    'Low': { bg: 'rgba(67,160,71,0.15)', border: 'rgba(67,160,71,0.4)', text: '#43A047' },
    'Average': { bg: 'rgba(255,179,0,0.15)', border: 'rgba(255,179,0,0.4)', text: '#FFB300' },
    'High': { bg: 'rgba(255,107,53,0.15)', border: 'rgba(255,107,53,0.4)', text: '#FF6B35' },
    'Critical':   { bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.4)', text: '#EF4444' },
  };
  const c = colors[level] ?? colors['Average'];
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 14px', borderRadius: '4px', background: c.bg, border: `1px solid ${c.border}` }}>
      <AlertTriangle size={14} style={{ color: c.text }} />
      <span style={{ color: c.text, fontFamily: T.fontMono, fontSize: '12px', fontWeight: 700 }}>{level} — {score}%</span>
    </div>
  );
}

// ─── Chat message ─────────────────────────────────────────────────────────────
interface ChatMsg { role: 'user' | 'assistant'; content: string; ts: number; }

function ChatMessage({ msg, onCopy }: { msg: ChatMsg; onCopy: (t: string) => void }) {
  const isUser = msg.role === 'user';
  return (
    <div style={{ display: 'flex', gap: '10px', justifyContent: isUser ? 'flex-end' : 'flex-start', marginBottom: '12px' }}>
      {!isUser && (
        <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'rgba(66,165,245,0.15)', border: '1px solid rgba(66,165,245,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <Bot size={16} style={{ color: T.blue }} />
        </div>
      )}
      <div style={{
        maxWidth: '80%', padding: '10px 14px', borderRadius: isUser ? '12px 12px 4px 12px' : '12px 12px 12px 4px',
        background: isUser ? 'rgba(66,165,245,0.15)' : T.card,
        border: `1px solid ${isUser ? 'rgba(66,165,245,0.3)' : T.border}`,
        color: T.text, fontSize: '13px', lineHeight: '1.6',
      }}>
        {isUser ? (
          <span>{msg.content}</span>
        ) : (
          <div style={{ position: 'relative' }}>
            <Streamdown>{msg.content}</Streamdown>
            <button
              onClick={() => onCopy(msg.content)}
              style={{ position: 'absolute', top: '-4px', left: '-4px', padding: '3px', borderRadius: '4px', background: 'transparent', border: 'none', cursor: 'pointer', color: T.textMuted, opacity: 0.6 }}
              title="Copy"
            >
              <Copy size={12} />
            </button>
          </div>
        )}
        <div style={{ fontSize: '10px', color: T.textMuted, marginTop: '4px', textAlign: isUser ? 'left' : 'right', fontFamily: T.fontMono }}>
          {new Date(msg.ts).toLocaleTimeString('ar-AE', { hour: '2-digit', minute: '2-digit' })}
        </div>
      </div>
      {isUser && (
        <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'rgba(171,71,188,0.15)', border: '1px solid rgba(171,71,188,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <User size={16} style={{ color: T.purple }} />
        </div>
      )}
    </div>
  );
}

// ─── Suggested questions ──────────────────────────────────────────────────────
const SUGGESTED = [
  'Which region has the highest risk now and what is the recommendation?',
  'How do current rainfall readings compare to the March 2026 event?',
  'What are the weaknesses in the drainage network?',
  'When is flood recession in Al Wathba forecasted?',
  'What is the difference in accuracy between the SAR model and Vision Transformer model?',
];

// ─── Clickable metric chip ────────────────────────────────────────────────────
function MetricChip({
  value, unit, label, color, onClick, pulse,
}: {
  value: string | number; unit?: string; label: string;
  color: string; onClick?: () => void; pulse?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      title={onClick ? `Click to view ${label} details` : undefined}
      style={{
        display: 'inline-flex', flexDirection: 'column', alignItems: 'center',
        gap: '2px', padding: '10px 16px', borderRadius: '8px',
        background: `${color}12`, border: `1px solid ${color}35`,
        cursor: onClick ? 'pointer' : 'default',
        transition: 'all 0.15s', minWidth: '90px',
        position: 'relative', overflow: 'hidden',
      }}
      onMouseEnter={e => { if (onClick) (e.currentTarget as HTMLElement).style.background = `${color}22`; }}
      onMouseLeave={e => { if (onClick) (e.currentTarget as HTMLElement).style.background = `${color}12`; }}
    >
      {pulse && (
        <div style={{
          position: 'absolute', top: '6px', left: '6px',
          width: '6px', height: '6px', borderRadius: '50%',
          background: color, animation: 'pulse 2s infinite',
        }} />
      )}
      <span style={{ fontSize: '22px', fontWeight: 800, color, fontFamily: 'Space Mono, monospace', lineHeight: 1 }}>
        {value}{unit && <span style={{ fontSize: '12px', fontWeight: 400, color: `${color}99` }}>{unit}</span>}
      </span>
      <span style={{ fontSize: '10px', color: `${color}99`, fontFamily: 'monospace', whiteSpace: 'nowrap' }}>{label}</span>
      {onClick && (
        <span style={{ fontSize: '8px', color: `${color}66`, marginTop: '1px' }}>↗ Details</span>
      )}
    </button>
  );
}

// ─── Bullet list parser ───────────────────────────────────────────────────────
function BulletList({ text, color }: { text: string; color: string }) {
  // Split on numbered items (1. 2. 3.) or newlines or Arabic bullets
  const raw = text
    .replace(/\*\*/g, '')
    .replace(/^#+\s*/gm, '')
    .split(/\n|(?=\d+\.\s)|(?=[-•]\s)/)
    .map(s => s.replace(/^[\d]+\.\s*/, '').replace(/^[-•]\s*/, '').trim())
    .filter(s => s.length > 8);

  const items = raw.length > 0 ? raw : [text.trim()];

  return (
    <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '7px' }}>
      {items.map((item, i) => (
        <li key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start' }}>
          <span style={{
            flexShrink: 0, width: '18px', height: '18px', borderRadius: '50%',
            background: `${color}18`, border: `1px solid ${color}40`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '9px', fontWeight: 700, color, fontFamily: 'monospace', marginTop: '1px',
          }}>{i + 1}</span>
          <span style={{ fontSize: '13px', color: '#D0E8F0', lineHeight: '1.55', fontFamily: 'Tajawal, sans-serif' }}>{item}</span>
        </li>
      ))}
    </ul>
  );
}

// ─── Executive View — Leadership Status ────────────────────────────────────────────
function ExecutiveView({
  summary,
  onGenerate,
  isPending,
  weatherSummary,
  onSwitchToAnalyst,
}: {
  summary: {
    title: string; riskLevel: string; riskScore: number;
    currentStatus: string; insights: string; recommendations: string;
    topRegion: string; keyMetric: string; generatedAt: string;
  } | null;
  onGenerate: () => void;
  isPending: boolean;
  weatherSummary: ReturnType<typeof computeWeatherSummary>;
  onSwitchToAnalyst: () => void;
}) {
  const [drillDown, setDrillDown] = useState<DrillDownType | null>(null);
  const [regionModal, setRegionModal] = useState<{ region: import('@/services/weatherApi').RegionWeather; metric: 'risk' | 'temp' | 'precip' } | null>(null);
  const { lang } = useLanguage();
  const isArExec = lang === 'ar';
  const execDir = isArExec ? 'rtl' : 'ltr';

  const riskColor = summary
    ? summary.riskScore >= 70 ? '#EF4444'
    : summary.riskScore >= 50 ? '#FF6B35'
    : '#FFB300'
    : T.amber;

  const riskBorder = summary
    ? summary.riskScore >= 70 ? 'rgba(239,68,68,0.4)'
    : summary.riskScore >= 50 ? 'rgba(255,107,53,0.4)'
    : 'rgba(255,179,0,0.35)'
    : 'rgba(66,165,245,0.35)';

  const stripGradient = summary
    ? summary.riskScore >= 70 ? 'linear-gradient(90deg, #EF4444, #FF6B35, #EF4444)'
    : summary.riskScore >= 50 ? 'linear-gradient(90deg, #FF6B35, #FFB300)'
    : 'linear-gradient(90deg, #FFB300, #4DD0E1)'
    : 'linear-gradient(90deg, #42A5F5, #4DD0E1)';

  // Live weather data for drill-down modals (same hook call - React deduplicates)
  const { data: wd2 } = useRealWeather();
  const liveRegions2 = wd2?.regions ?? [];
  const topRegionData = liveRegions2.find(r => r.nameAr === summary?.topRegion) ?? liveRegions2[0] ?? null;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', direction: execDir, textAlign: isArExec ? 'right' : 'left' }}>

      {/* ══ STRIP ══ */}
      <div style={{
        height: '4px', background: stripGradient, borderRadius: '4px 4px 0 0',
        animation: summary && summary.riskScore >= 70 ? 'stripPulse 2s ease-in-out infinite' : 'none',
      }} />

      {/* ══ HEADER ══ */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '12px 18px', background: 'rgba(66,165,245,0.04)',
        borderBottom: `1px solid ${T.border}`,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Crown size={16} style={{ color: T.amber }} />
          <span style={{ fontSize: '14px', fontWeight: 700, color: T.text }}>{isArExec ? 'حالة القيادة' : 'Leadership Status'}</span>
          <span style={{
            fontSize: '9px', padding: '2px 7px', borderRadius: '3px',
            background: 'rgba(255,179,0,0.12)', border: '1px solid rgba(255,179,0,0.3)',
            color: T.amber, fontFamily: T.fontMono, fontWeight: 700,
          }}>{isArExec ? 'تنفيذي' : 'EXECUTIVE'}</span>
        </div>
        <div style={{ display: 'flex', gap: '6px' }}>
          <button onClick={onGenerate} disabled={isPending} style={{
            display: 'flex', alignItems: 'center', gap: '5px', padding: '6px 14px',
            borderRadius: '4px', background: isPending ? 'rgba(66,165,245,0.06)' : 'rgba(66,165,245,0.18)',
            color: T.blue, border: `1px solid ${T.borderAct}`, fontSize: '11px', fontWeight: 600,
            cursor: isPending ? 'not-allowed' : 'pointer',
          }}>
            {isPending ? <><Loader2 size={12} style={{ animation: 'spin 1s linear infinite' }} /> {isArExec ? 'تحليل...' : 'Analysis...'}</> : <><Brain size={12} /> {summary ? (isArExec ? 'تحديث' : 'Update') : (isArExec ? 'توليد' : 'Generate')}</>}
          </button>
          <button onClick={onSwitchToAnalyst} style={{
            display: 'flex', alignItems: 'center', gap: '5px', padding: '6px 10px',
            borderRadius: '4px', background: 'transparent', border: `1px solid ${T.border}`,
            color: T.textMuted, fontSize: '11px', cursor: 'pointer',
          }}>
            <EyeOff size={11} /> {isArExec ? 'محلل' : 'Analyst'}
          </button>
        </div>
      </div>

      {/* ══ EMPTY STATE ══ */}
      {!summary && !isPending && (
        <div style={{ padding: '40px 32px', textAlign: 'center' }}>
          <Crown size={40} style={{ color: T.textMuted, margin: '0 auto 12px', display: 'block' }} />
          <p style={{ color: T.text, fontSize: '14px', fontWeight: 600, marginBottom: '6px' }}>{isArExec ? 'الملخص التنفيذي جاهز' : 'Executive Brief ready'}</p>
          <p style={{ color: T.textMuted, fontSize: '12px', marginBottom: '18px' }}>
            {weatherSummary ? liveRegions2.length : 90} {isArExec ? 'منطقة · بيانات حية · وقت القراءة ≤30 ثانية' : 'Region · Live Data · reading time ≤30 seconds'}
          </p>
          <button onClick={onGenerate} style={{
            display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '10px 24px',
            borderRadius: '6px', background: 'rgba(66,165,245,0.18)', color: T.blue,
            border: `1px solid ${T.borderAct}`, fontSize: '13px', fontWeight: 600, cursor: 'pointer',
          }}>
            <Brain size={15} /> {isArExec ? 'توليد الملخص' : 'Generate Brief'}
          </button>
        </div>
      )}

      {/* ══ LOADING ══ */}
      {isPending && (
        <div style={{ padding: '40px 32px', textAlign: 'center' }}>
          <Loader2 size={36} style={{ color: T.blue, margin: '0 auto 12px', display: 'block', animation: 'spin 1s linear infinite' }} />
          <p style={{ color: T.textSub, fontSize: '13px', fontWeight: 600 }}>{isArExec ? 'جارٍ تحليل البيانات الحية...' : 'Analyzing live data...'}</p>
        </div>
      )}

      {/* ══ CONTENT ══ */}
      {summary && (
        <div>

          {/* ── ROW 1: Key Metrics (clickable) ── */}
          <div style={{
            padding: '16px 20px',
            borderBottom: `1px solid ${T.border}`,
            background: 'rgba(0,0,0,0.1)',
          }}>
            <div style={{ fontSize: '9px', color: T.textMuted, fontFamily: T.fontMono, letterSpacing: '0.1em', marginBottom: '10px' }}>
              {isArExec ? 'المؤشرات الرئيسية — اضغط على أي رقم للتفاصيل' : 'Key Indices — click any number for details'}
            </div>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'flex-start' }}>
              {/* risk index */}
              <MetricChip
                value={summary.riskScore} unit="%"
                label={isArExec ? 'مؤشر الخطر' : 'risk index'}
                color={riskColor}
                pulse={summary.riskScore >= 50}
                onClick={() => setDrillDown('risk')}
              />
              {/* Rainfall */}
              {weatherSummary && (
                <MetricChip
                  value={weatherSummary.totalPrecip} unit=" mm"
                  label={isArExec ? 'هطول 24 ساعة' : '24hr Rainfall'}
                  color={T.blue}
                  onClick={() => setDrillDown('totalPrecip')}
                />
              )}
              {/* Alerts */}
              {weatherSummary && (
                <MetricChip
                  value={weatherSummary.activeAlerts}
                  label={isArExec ? 'تنبيه نشط' : 'Active Alert'}
                  color={weatherSummary.activeAlerts > 0 ? '#EF4444' : T.green}
                  onClick={() => setDrillDown('alerts')}
                />
              )}
              {/* Highest Risk Region */}
              <button
                onClick={() => topRegionData && setRegionModal({ region: topRegionData, metric: 'risk' })}
                title="click to view details - Highest Risk Region"
                style={{
                  display: 'inline-flex', flexDirection: 'column', alignItems: 'center', gap: '2px',
                  padding: '10px 16px', borderRadius: '8px',
                  background: `${T.teal}12`, border: `1px solid ${T.teal}35`,
                  cursor: 'pointer', transition: 'all 0.15s', minWidth: '90px',
                }}
                onMouseEnter={e => (e.currentTarget as HTMLElement).style.background = `${T.teal}22`}
                onMouseLeave={e => (e.currentTarget as HTMLElement).style.background = `${T.teal}12`}
              >
                <MapPin size={14} style={{ color: T.teal }} />
                <span style={{ fontSize: '14px', fontWeight: 700, color: T.teal, fontFamily: 'Tajawal, sans-serif', lineHeight: 1.2, textAlign: 'center' }}>
                  {summary.topRegion}
                </span>
                <span style={{ fontSize: '10px', color: `${T.teal}99`, fontFamily: 'monospace', whiteSpace: 'nowrap' }}>{isArExec ? 'أعلى خطورة' : 'Highest Risk'}</span>
                <span style={{ fontSize: '8px', color: `${T.teal}66`, marginTop: '1px' }}>{isArExec ? '↗ تفاصيل' : '↗ Details'}</span>
              </button>
              {/* Time */}
              <div style={{
                display: 'inline-flex', flexDirection: 'column', alignItems: 'center', gap: '2px',
                padding: '10px 16px', borderRadius: '8px',
                background: `${T.textMuted}08`, border: `1px solid ${T.textMuted}20`,
                minWidth: '90px',
              }}>
                <Clock size={14} style={{ color: T.textMuted }} />
                <span style={{ fontSize: '13px', fontWeight: 700, color: T.textSub, fontFamily: 'monospace', lineHeight: 1.2 }}>
                  {summary.generatedAt.split(',')[1]?.trim() ?? summary.generatedAt}
                </span>
                <span style={{ fontSize: '10px', color: T.textMuted, fontFamily: 'monospace', whiteSpace: 'nowrap' }}>{isArExec ? 'آخر تحديث' : 'Last Update'}</span>
              </div>
            </div>
          </div>

          {/* ── ROW 2: Immediate Actions (points) ── */}
          <div style={{
            padding: '14px 20px',
            background: summary.riskScore >= 70
              ? 'rgba(239,68,68,0.07)'
              : summary.riskScore >= 50
              ? 'rgba(255,107,53,0.07)'
              : 'rgba(255,179,0,0.05)',
            borderBottom: `1px solid ${T.border}`,
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '10px' }}>
              <Zap size={13} style={{ color: riskColor }} />
              <span style={{ fontSize: '10px', fontWeight: 700, color: riskColor, fontFamily: T.fontMono, letterSpacing: '0.08em' }}>
                {isArExec ? 'الإجراءات الفورية' : 'Immediate Actions'}
              </span>
              <span style={{
                fontSize: '9px', padding: '1px 8px', borderRadius: '3px',
                background: `${riskColor}18`, border: `1px solid ${riskBorder}`,
                color: riskColor, fontFamily: T.fontMono, fontWeight: 700,
              }}>
                {summary.riskLevel === 'Critical' ? (isArExec ? '🔴 أولوية حرجة' : '🔴 Critical Priority') : summary.riskLevel === 'High' ? (isArExec ? '🟠 أولوية عالية' : '🟠 High Priority') : (isArExec ? '🟡 مراقبة' : '🟡 Monitoring')}
              </span>
            </div>
            <BulletList text={summary.recommendations} color={riskColor} />
          </div>

          {/* ── ROW 3: Status + Insights (side by side) ── */}
          <div style={{
            display: 'grid', gridTemplateColumns: '1fr 1fr',
            borderBottom: `1px solid ${T.border}`,
          }}>
            <div style={{ padding: '14px 18px', borderLeft: `1px solid ${T.border}` }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '5px', marginBottom: '10px' }}>
                <Shield size={12} style={{ color: T.blue }} />
                <span style={{ fontSize: '10px', fontWeight: 700, color: T.blue, fontFamily: T.fontMono, letterSpacing: '0.08em' }}>{isArExec ? 'الحالة الراهنة' : 'Current Status'}</span>
              </div>
              <BulletList text={summary.currentStatus} color={T.blue} />
            </div>
            <div style={{ padding: '14px 18px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '5px', marginBottom: '10px' }}>
                <Target size={12} style={{ color: T.amber }} />
                <span style={{ fontSize: '10px', fontWeight: 700, color: T.amber, fontFamily: T.fontMono, letterSpacing: '0.08em' }}>{isArExec ? 'الرؤى والمخاطر' : 'Insights & Risks'}</span>
              </div>
              <BulletList text={summary.insights} color={T.amber} />
            </div>
          </div>

          {/* ── FOOTER ── */}
          <div style={{
            padding: '8px 18px', display: 'flex', alignItems: 'center',
            justifyContent: 'space-between', background: 'rgba(0,0,0,0.12)',
          }}>
            <span style={{ fontSize: '10px', color: T.textMuted, fontFamily: T.fontMono }}>{summary.title}</span>
            <button
              onClick={() => {
                navigator.clipboard.writeText(
                  `${summary.title}\n\n⚡ Immediate Actions:\n${summary.recommendations}\n\n📊 Current Status:\n${summary.currentStatus}\n\n🎯 Insights:\n${summary.insights}`
                );
                toast.success(isArExec ? 'تم نسخ الملخص' : 'Brief copied');
              }}
              style={{
                display: 'flex', alignItems: 'center', gap: '4px', padding: '4px 10px',
                borderRadius: '4px', background: 'transparent', border: `1px solid ${T.border}`,
                color: T.textMuted, fontSize: '10px', cursor: 'pointer',
              }}
            >
              <Copy size={10} /> {isArExec ? 'نسخ' : 'Copy'}
            </button>
          </div>
        </div>
      )}

      {/* ══ DRILL-DOWN MODALS ══ */}
      {drillDown && liveRegions2.length > 0 && (
        <KPIDrillDown type={drillDown} regions={liveRegions2} onClose={() => setDrillDown(null)} />
      )}
      {regionModal && (
        <RegionDetailModal region={regionModal.region} metric={regionModal.metric} onClose={() => setRegionModal(null)} />
      )}
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function ReportsPage() {
  const { lang } = useLanguage();
  const isAr = lang === 'ar';
  const pageDir = isAr ? 'rtl' : 'ltr';

  const rainfallData14 = useMemo(() => gen14DayRainfall(), []);
  const riskTrend14    = useMemo(() => gen14DayRiskTrend(), []);
  const todayLabel     = rainfallData14.find(d => d.isCurrent)?.time ?? 'Today';
  const todayRiskLabel = riskTrend14.find(d => d.isCurrent)?.date ?? 'Today';

  const { data: weatherData } = useRealWeather();
  const weatherSummary = computeWeatherSummary(weatherData);
  // Single Source of Truth: use live regions from weatherApi, fallback to empty array
  const liveRegions = weatherData?.regions ?? [];
  // Adapter: map RegionWeather to Region-compatible shape for charts/exports
  const regions = liveRegions.map(r => ({
    nameAr: r.nameAr,
    nameEn: r.nameEn,
    rainfall: r.totalLast24h,
    floodRisk: r.floodRisk,
    waterAccumulation: Math.round(r.totalLast24h * 50000 * 0.0018),
    alertLevel: r.alertLevel,
  }));

  // ── View mode ──
  const [viewMode, setViewMode] = useState<'executive' | 'analyst'>('executive');

  // ── Executive Summary state ──
  const [summary, setSummary] = useState<{
    title: string; riskLevel: string; riskScore: number;
    currentStatus: string; insights: string; recommendations: string;
    topRegion: string; keyMetric: string; generatedAt: string;
  } | null>(null);
  const [summaryExpanded, setSummaryExpanded] = useState(true);
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateSummaryMutation = trpc.reports.generateExecutiveSummary.useMutation({
    onSuccess: (res) => {
      if (res.success && res.data) {
        setSummary(res.data as typeof summary);
        toast.success(lang === 'ar' ? 'تم توليد الملخص التنفيذي' : 'Executive brief generated', { description: lang === 'ar' ? 'بناءً على بيانات المنصة الحية' : 'based on live platform data' });
      } else {
        toast.error('Failed to generate summary', { description: 'Verify system connection' });
      }
    },
    onError: () => toast.error('System connection error'),
  });

  const handleGenerateSummary = () => {
    const ws = weatherSummary ? {
      rainfall: weatherSummary.totalPrecip,
      temperature: weatherSummary.avgTemp,
      humidity: 65,
      windSpeed: 15,
    } : undefined;

    generateSummaryMutation.mutate({
      lang: lang as 'ar' | 'en',
      regions: regions.map(r => ({
        nameAr: r.nameAr,
        rainfall: r.rainfall,
        floodRisk: r.floodRisk,
        waterAccumulation: r.waterAccumulation,
      })),
      systemStats: {
        totalMonitoredArea: systemStats.totalMonitoredArea,
        alertsLast24h: systemStats.alertsLast24h,
        avgResponseTime: systemStats.avgResponseTime,
        dataProcessed: systemStats.dataProcessed,
        overallRisk: Math.round(regions.reduce((s, r) => s + r.floodRisk, 0) / regions.length),
      },
      weatherSummary: ws,
      eventContext: lang === 'ar' ? 'عاصفة مارس 2026 — أمطار غير مسبوقة في الإمارات، أعلى قراءة: غياثي 91.0 مم' : 'Storm March 2026 — Unprecedented rain in UAE, highest reading: Ghayathi 91.0 mm',
    });
  };

  // ── Chat state ──
  const [chatHistory, setChatHistory] = useState<ChatMsg[]>(() => [{
    role: 'assistant',
    content: lang === 'ar'
      ? `مرحباً! أنا مستشار FloodSat الذكي. لدي صلاحية الوصول الكاملة إلى بيانات المنصة الحية — قراءات الأمطار، مؤشرات الخطر، إحصائيات الأقمار الصناعية، وتحليلات الفيضانات في إمارة أبوظبي.\n\n**كيف يمكنني مساعدتك؟** يمكنني الإجابة على أي سؤال متعلق بالوضع الراهن، التوقعات، مقارنات تاريخية، أو التوصيات التشغيلية.`
      : `Hello! I am the FloodSat AI advisor. I have full access to live platform data — rainfall readings, risk indices, satellite statistics, and flood analyses in Abu Dhabi Emirate.\n\n**How can I help you?** I can answer any question related to current status, forecasts, date comparisons, or operational recommendations.`,
    ts: Date.now(),
  }]);
  const [chatInput, setChatInput] = useState('');
  const chatEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const sendMessageMutation = trpc.chat.sendMessage.useMutation({
    onSuccess: (res) => {
      setChatHistory(prev => [...prev, {
        role: 'assistant',
        content: res.reply,
        ts: Date.now(),
      }]);
    },
    onError: () => {
      setChatHistory(prev => [...prev, {
        role: 'assistant',
        content: 'Sorry, a connection error occurred. Please try again.',
        ts: Date.now(),
      }]);
    },
  });

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatHistory]);

  const handleSend = (text?: string) => {
    const msg = (text ?? chatInput).trim();
    if (!msg || sendMessageMutation.isPending) return;

    const userMsg: ChatMsg = { role: 'user', content: msg, ts: Date.now() };
    setChatHistory(prev => [...prev, userMsg]);
    setChatInput('');

    const ws = weatherSummary ? {
      rainfall: weatherSummary.totalPrecip,
      temperature: weatherSummary.avgTemp,
      humidity: 65,
      windSpeed: 15,
    } : undefined;

    sendMessageMutation.mutate({
      message: msg,
      lang: lang as 'ar' | 'en',
      history: chatHistory.slice(-10).map(h => ({ role: h.role, content: h.content })),
      platformContext: {
        regions: regions.map(r => ({
          nameAr: r.nameAr,
          rainfall: r.rainfall,
          floodRisk: r.floodRisk,
          waterAccumulation: r.waterAccumulation,
        })),
        systemStats: {
          totalMonitoredArea: systemStats.totalMonitoredArea,
          alertsLast24h: systemStats.alertsLast24h,
          avgResponseTime: systemStats.avgResponseTime,
          dataProcessed: systemStats.dataProcessed,
        },
        weatherSummary: ws,
        executiveSummary: summary
          ? `${summary.currentStatus}\n\n${summary.insights}\n\n${summary.recommendations}`
          : undefined,
      },
    });
  };

  const handleCopyMsg = (text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };

  const handleExportFull = async () => {
    setExporting(true);
    toast.info('Exporting comprehensive report...');
    await new Promise(r => setTimeout(r, 600));
    const now = new Date().toLocaleString('ar-AE');
    downloadCSV(`FloodSat_Report_${new Date().toISOString().slice(0, 10)}.csv`,
      regions.map(r => ({ 'Region': r.nameAr, 'rainfall (mm/hr)': r.rainfall, 'risk index (%)': r.floodRisk, 'Water accumulation (m²)': r.waterAccumulation, 'Time Report': now }))
    );
    setExporting(false);
    toast.success('Report exported successfully');
  };

  const tooltipStyle = { background: T.card, border: `1px solid ${T.borderAct}`, borderRadius: '6px', fontSize: '11px', direction: pageDir as 'rtl' | 'ltr' };

  return (
    <div className="space-y-6" dir={pageDir} style={{ color: T.text, textAlign: isAr ? 'right' : 'left' }}>

      {/* ── Header ── */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <BarChart3 size={20} style={{ color: T.blue }} />
            <h1 style={{ fontFamily: T.fontHead, fontSize: '20px', fontWeight: 700, color: T.text, margin: 0 }}>
              {isAr ? 'مركز التقارير الذكية ودعم القرار' : 'Smart Reports and Decision Center'}
            </h1>
          </div>
          <p style={{ fontSize: '12px', color: T.textMuted, marginTop: '2px' }}>
            {viewMode === 'executive'
              ? (isAr ? 'حالة القيادة العليا · ملخص تنفيذي · وقت القراءة ≤30 ثانية' : 'Senior Leadership Status · Executive briefing · reading time ≤30 seconds')
              : (isAr ? 'حالة المحلل · ملخص ذكاء اصطناعي · لوحة تفاعلية · بيانات 14 يوماً' : 'Analyst Status · AI executive summary · interactive dashboard · 14-day live data')}
          </p>
        </div>
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' }}>
          {/* View mode toggle */}
          <div style={{
            display: 'flex', borderRadius: '6px', overflow: 'hidden',
            border: `1px solid ${T.border}`,
          }}>
            <button
              onClick={() => setViewMode('executive')}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 14px', fontSize: '12px', fontWeight: 600,
                background: viewMode === 'executive' ? 'rgba(255,179,0,0.18)' : 'transparent',
                color: viewMode === 'executive' ? T.amber : T.textMuted,
                border: 'none', cursor: 'pointer',
                borderLeft: viewMode === 'executive' ? `2px solid ${T.amber}` : '2px solid transparent',
              }}
            >
              <Crown size={13} /> {isAr ? 'قيادة' : 'leadership'}
            </button>
            <button
              onClick={() => setViewMode('analyst')}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 14px', fontSize: '12px', fontWeight: 600,
                background: viewMode === 'analyst' ? 'rgba(66,165,245,0.18)' : 'transparent',
                color: viewMode === 'analyst' ? T.blue : T.textMuted,
                border: 'none', cursor: 'pointer',
                borderLeft: viewMode === 'analyst' ? `2px solid ${T.blue}` : '2px solid transparent',
              }}
            >
              <Eye size={13} /> {isAr ? 'محلل' : 'Analyst'}
            </button>
          </div>
          <button onClick={() => window.print()} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '7px 14px', borderRadius: '4px', background: 'rgba(171,71,188,0.12)', color: '#CE93D8', border: '1px solid rgba(171,71,188,0.3)', fontSize: '12px', cursor: 'pointer' }}>
            <FileDown size={13} /> {isAr ? 'تصدير PDF' : 'Export PDF'}
          </button>
          <button onClick={handleExportFull} disabled={exporting} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '7px 14px', borderRadius: '4px', background: 'rgba(66,165,245,0.12)', color: T.blue, border: `1px solid ${T.borderAct}`, fontSize: '12px', cursor: 'pointer', opacity: exporting ? 0.7 : 1 }}>
            <Download size={13} /> {exporting ? (isAr ? 'جارٍ التصدير...' : 'Exporting...') : (isAr ? 'تصدير CSV' : 'Export CSV')}
          </button>
        </div>
      </div>

      {/* ══ EXECUTIVE VIEW ══ */}
      {viewMode === 'executive' && (
        <div style={{
          background: T.card,
          border: `1px solid ${summary
            ? summary.riskScore >= 70 ? 'rgba(239,68,68,0.4)'
            : summary.riskScore >= 50 ? 'rgba(255,107,53,0.4)'
            : 'rgba(255,179,0,0.3)'
            : T.borderAct}`,
          borderRadius: '8px', overflow: 'hidden',
        }}>
          <ExecutiveView
            summary={summary}
            onGenerate={handleGenerateSummary}
            isPending={generateSummaryMutation.isPending}
            weatherSummary={weatherSummary}
            onSwitchToAnalyst={() => setViewMode('analyst')}
          />
        </div>
      )}

      {/* ══ ANALYST VIEW ══ */}
      {viewMode === 'analyst' && (
        <>
          {/* ── Executive Summary Card (Analyst mode) ── */}
          <div style={{ background: T.card, border: `1px solid ${T.borderAct}`, borderRadius: '8px', overflow: 'hidden' }}>
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 18px', borderBottom: `1px solid ${T.border}`, background: 'rgba(66,165,245,0.05)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <Sparkles size={18} style={{ color: T.blue }} />
                <span style={{ fontFamily: T.fontHead, fontSize: '15px', fontWeight: 700, color: T.text }}>{isAr ? 'الملخص التنفيذي الذكي' : 'Smart Executive Summary'}</span>
                {summary && <RiskBadge level={summary.riskLevel} score={summary.riskScore} />}
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                {summary && (
                  <button onClick={() => setSummaryExpanded(v => !v)} style={{ padding: '4px 8px', borderRadius: '4px', background: 'transparent', border: `1px solid ${T.border}`, color: T.textMuted, cursor: 'pointer' }}>
                    {summaryExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                  </button>
                )}
                <button
                  onClick={() => setViewMode('executive')}
                  style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '7px 12px', borderRadius: '4px', background: 'rgba(255,179,0,0.1)', color: T.amber, border: '1px solid rgba(255,179,0,0.3)', fontSize: '11px', cursor: 'pointer' }}
                >
                  <Crown size={12} /> {isAr ? 'حالة القيادة' : 'Leadership Status'}
                </button>
                <button
                  onClick={handleGenerateSummary}
                  disabled={generateSummaryMutation.isPending}
                  style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '7px 16px', borderRadius: '4px', background: generateSummaryMutation.isPending ? 'rgba(66,165,245,0.08)' : 'rgba(66,165,245,0.18)', color: T.blue, border: `1px solid ${T.borderAct}`, fontSize: '12px', fontWeight: 600, cursor: generateSummaryMutation.isPending ? 'not-allowed' : 'pointer', transition: 'all 0.2s' }}
                >
                  {generateSummaryMutation.isPending
                    ? <><Loader2 size={13} style={{ animation: 'spin 1s linear infinite' }} /> {isAr ? 'جارٍ التوليد...' : 'Generating...'}</>
                    : <><Brain size={13} /> {summary ? (isAr ? 'تحديث الملخص' : 'Update Summary') : (isAr ? 'توليد الملخص' : 'Generate Summary')}</>
                  }
                </button>
              </div>
            </div>

            {/* Content */}
            {!summary && !generateSummaryMutation.isPending && (
              <div style={{ padding: '32px', textAlign: 'center' }}>
                <Brain size={40} style={{ color: T.textMuted, margin: '0 auto 12px', display: 'block' }} />
                <p style={{ color: T.textMuted, fontSize: '13px', marginBottom: '6px' }}>{isAr ? 'اضغط "توليد الملخص" لإنشاء ملخص تنفيذي بالذكاء الاصطناعي' : 'Press "Generate Summary" to create an AI executive summary'}</p>
                <p style={{ color: T.textMuted, fontSize: '11px' }}>{isAr ? `يحلل الذكاء الاصطناعي بيانات ${regions.length} منطقة + أحوال الطقس الحية + إحصائيات النظام` : `AI analyzes data from ${regions.length} regions + live weather conditions + system statistics`}</p>
              </div>
            )}

            {generateSummaryMutation.isPending && (
              <div style={{ padding: '32px', textAlign: 'center' }}>
                <Loader2 size={32} style={{ color: T.blue, margin: '0 auto 12px', display: 'block', animation: 'spin 1s linear infinite' }} />
                <p style={{ color: T.textSub, fontSize: '13px' }}>{isAr ? 'جارٍ تحليل البيانات الحية...' : 'AI analyzing live data...'}</p>
                <p style={{ color: T.textMuted, fontSize: '11px', marginTop: '4px' }}>{isAr ? `قراءة ${regions.length} منطقة · ${systemStats.alertsLast24h} تنبيه · ${systemStats.dataProcessed} بيانات` : `Reading ${regions.length} Region · ${systemStats.alertsLast24h} Alert · ${systemStats.dataProcessed} Data`}</p>
              </div>
            )}

            {summary && summaryExpanded && (
              <div style={{ padding: '0' }}>
                {/* TIER 1 */}
                <div style={{
                  padding: '18px 24px',
                  background: summary.riskLevel === 'Critical'
                    ? 'linear-gradient(135deg, rgba(239,68,68,0.18) 0%, rgba(239,68,68,0.06) 100%)'
                    : summary.riskLevel === 'High'
                    ? 'linear-gradient(135deg, rgba(255,107,53,0.18) 0%, rgba(255,107,53,0.06) 100%)'
                    : 'linear-gradient(135deg, rgba(255,179,0,0.15) 0%, rgba(255,179,0,0.04) 100%)',
                  borderBottom: `1px solid ${T.border}`,
                }}>
                  <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px' }}>
                    <div style={{
                      width: '44px', height: '44px', borderRadius: '8px', flexShrink: 0,
                      background: summary.riskLevel === 'Critical' ? 'rgba(239,68,68,0.2)'
                        : summary.riskLevel === 'High' ? 'rgba(255,107,53,0.2)' : 'rgba(255,179,0,0.2)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      border: `1px solid ${summary.riskLevel === 'Critical' ? 'rgba(239,68,68,0.4)' : summary.riskLevel === 'High' ? 'rgba(255,107,53,0.4)' : 'rgba(255,179,0,0.4)'}`,
                    }}>
                      <Zap size={22} style={{ color: summary.riskLevel === 'Critical' ? '#EF4444' : summary.riskLevel === 'High' ? T.red : T.amber }} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                        <span style={{ fontSize: '10px', fontWeight: 700, color: T.textMuted, fontFamily: T.fontMono, letterSpacing: '0.1em', textTransform: 'uppercase' }}>{isAr ? 'الإجراءات الفورية المطلوبة' : 'Required Immediate Actions'}</span>
                        <span style={{ fontSize: '10px', padding: '2px 8px', borderRadius: '3px', background: 'rgba(255,255,255,0.06)', color: T.textMuted, fontFamily: T.fontMono }}>{isAr ? 'أولوية حرجة' : 'Critical Priority'}</span>
                      </div>
                      <div style={{ fontSize: '14px', fontWeight: 600, color: T.text, lineHeight: '1.6' }}>
                        <Streamdown>{summary.recommendations}</Streamdown>
                      </div>
                    </div>
                  </div>
                </div>

                {/* TIER 2 */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', borderBottom: `1px solid ${T.border}` }}>
                  <div style={{ padding: '20px 24px', borderLeft: `1px solid ${T.border}`, textAlign: 'center' }}>
                    <div style={{ fontSize: '48px', fontWeight: 800, lineHeight: 1, fontFamily: T.fontMono, color: summary.riskScore >= 70 ? '#EF4444' : summary.riskScore >= 50 ? T.red : T.amber, marginBottom: '6px' }}>
                      {summary.riskScore}<span style={{ fontSize: '20px', color: T.textMuted }}>%</span>
                    </div>
                    <div style={{ fontSize: '11px', color: T.textMuted, fontFamily: T.fontMono }}>{isAr ? 'مؤشر الخطر الإجمالي' : 'total risk index'}</div>
                    <div style={{ marginTop: '8px' }}><RiskBadge level={summary.riskLevel} score={summary.riskScore} /></div>
                  </div>
                  <div style={{ padding: '20px 24px', borderLeft: `1px solid ${T.border}`, textAlign: 'center' }}>
                    <div style={{ fontSize: '22px', fontWeight: 700, color: T.blue, lineHeight: 1.2, marginBottom: '6px', fontFamily: T.fontHead }}>{summary.topRegion}</div>
                    <div style={{ fontSize: '11px', color: T.textMuted, fontFamily: T.fontMono }}>{isAr ? 'المنطقة الأعلى خطورة' : 'Region Highest Risk'}</div>
                    <div style={{ marginTop: '8px', fontSize: '12px', color: T.textSub, fontFamily: T.fontMono }}>{summary.keyMetric}</div>
                  </div>
                  <div style={{ padding: '20px 24px', textAlign: 'center' }}>
                    <div style={{ fontSize: '18px', fontWeight: 700, color: T.teal, lineHeight: 1.2, marginBottom: '6px', fontFamily: T.fontMono }}>
                      {summary.generatedAt.split(',')[1]?.trim() ?? summary.generatedAt}
                    </div>
                    <div style={{ fontSize: '11px', color: T.textMuted, fontFamily: T.fontMono }}>{isAr ? 'آخر تحديث' : 'Last Update'}</div>
                    <div style={{ marginTop: '8px', fontSize: '11px', color: T.textMuted }}>{regions.length} {isAr ? 'منطقة · بيانات حية' : 'Region · live data'}</div>
                  </div>
                </div>

                {/* TIER 3 */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', borderBottom: `1px solid ${T.border}` }}>
                  <div style={{ padding: '16px 24px', borderLeft: `1px solid ${T.border}` }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '10px' }}>
                      <TrendingUp size={13} style={{ color: T.blue }} />
                      <span style={{ fontSize: '10px', fontWeight: 700, color: T.blue, fontFamily: T.fontMono, letterSpacing: '0.08em' }}>{isAr ? 'الحالة الراهنة' : 'Current Status'}</span>
                    </div>
                    <div style={{ fontSize: '12px', lineHeight: '1.75', color: T.text }}>
                      <Streamdown>{summary.currentStatus}</Streamdown>
                    </div>
                  </div>
                  <div style={{ padding: '16px 24px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '10px' }}>
                      <TrendingUp size={13} style={{ color: T.amber }} />
                      <span style={{ fontSize: '10px', fontWeight: 700, color: T.amber, fontFamily: T.fontMono, letterSpacing: '0.08em' }}>{isAr ? 'الرؤى والمخاطر' : 'Insights & Risks'}</span>
                    </div>
                    <div style={{ fontSize: '12px', lineHeight: '1.7', color: T.text }}>
                      <Streamdown>{summary.insights}</Streamdown>
                    </div>
                  </div>
                </div>

                {/* Footer */}
                <div style={{ padding: '10px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'rgba(0,0,0,0.15)' }}>
                  <span style={{ fontSize: '11px', color: T.textMuted, fontFamily: T.fontMono }}>{summary.title}</span>
                  <button
                    onClick={() => handleCopyMsg(`${summary.title}\n\nImmediate Actions:\n${summary.recommendations}\n\nCurrent Status:\n${summary.currentStatus}\n\ninsights:\n${summary.insights}`)}
                    style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '5px 12px', borderRadius: '4px', background: 'transparent', border: `1px solid ${T.border}`, color: T.textMuted, fontSize: '11px', cursor: 'pointer' }}
                  >
                    {copied ? <><Check size={11} /> {isAr ? 'تم النسخ' : 'copied'}</> : <><Copy size={11} /> {isAr ? 'نسخ الملخص' : 'copy summary'}</>}
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* ── AI Chat ── */}
          <div style={{ background: T.card, border: `1px solid ${T.borderAct}`, borderRadius: '8px', overflow: 'hidden' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 18px', borderBottom: `1px solid ${T.border}`, background: 'rgba(171,71,188,0.05)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <MessageSquare size={18} style={{ color: T.purple }} />
                <span style={{ fontFamily: T.fontHead, fontSize: '15px', fontWeight: 700, color: T.text }}>{isAr ? 'مستشار FloodSat الذكي' : 'FloodSat AI Advisor'}</span>
                <div style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '3px 8px', borderRadius: '3px', background: 'rgba(67,160,71,0.12)', border: '1px solid rgba(67,160,71,0.3)' }}>
                  <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: T.green, animation: 'pulse 2s infinite' }} />
                  <span style={{ fontSize: '10px', color: T.green, fontFamily: T.fontMono }}>{isAr ? 'متصل بالبيانات الحية' : 'connected to live data'}</span>
                </div>
              </div>
              <button
                onClick={() => setChatHistory([{ role: 'assistant', content: isAr ? 'تم مسح المحادثة. كيف يمكنني مساعدتك؟' : 'Conversation cleared. How can I help you?', ts: Date.now() }])}
                style={{ padding: '4px 10px', borderRadius: '4px', background: 'transparent', border: `1px solid ${T.border}`, color: T.textMuted, fontSize: '11px', cursor: 'pointer' }}
              >
                {isAr ? 'مسح' : 'Clear'}
              </button>
            </div>

            <div style={{ height: '340px', overflowY: 'auto', padding: '16px', scrollBehavior: 'smooth' }}>
              {chatHistory.map((msg, i) => (
                <ChatMessage key={i} msg={msg} onCopy={handleCopyMsg} />
              ))}
              {sendMessageMutation.isPending && (
                <div style={{ display: 'flex', gap: '10px', marginBottom: '12px' }}>
                  <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'rgba(66,165,245,0.15)', border: '1px solid rgba(66,165,245,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                    <Bot size={16} style={{ color: T.blue }} />
                  </div>
                  <div style={{ padding: '10px 14px', borderRadius: '12px 12px 12px 4px', background: T.card, border: `1px solid ${T.border}`, display: 'flex', gap: '4px', alignItems: 'center' }}>
                    {[0, 1, 2].map(i => (
                      <div key={i} style={{ width: '6px', height: '6px', borderRadius: '50%', background: T.blue, animation: `bounce 1.2s ${i * 0.2}s infinite` }} />
                    ))}
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            <div style={{ padding: '8px 16px', borderTop: `1px solid ${T.border}`, display: 'flex', gap: '6px', overflowX: 'auto', flexWrap: 'nowrap' }}>
              {SUGGESTED.map((q, i) => (
                <button
                  key={i}
                  onClick={() => handleSend(q)}
                  disabled={sendMessageMutation.isPending}
                  style={{ flexShrink: 0, padding: '5px 12px', borderRadius: '20px', background: 'rgba(66,165,245,0.08)', border: `1px solid rgba(66,165,245,0.2)`, color: T.textSub, fontSize: '11px', cursor: 'pointer', whiteSpace: 'nowrap', transition: 'all 0.15s' }}
                >
                  {q}
                </button>
              ))}
            </div>

            <div style={{ padding: '12px 16px', borderTop: `1px solid ${T.border}`, display: 'flex', gap: '8px' }}>
              <input
                ref={inputRef}
                value={chatInput}
                onChange={e => setChatInput(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); } }}
                placeholder={isAr ? 'اسأل عن الحالة الراهنة والتوقعات والمناطق المتأثرة...' : 'Ask about current status, forecasts, affected areas, recommendations...'}
                disabled={sendMessageMutation.isPending}
                style={{
                  flex: 1, padding: '10px 14px', borderRadius: '6px',
                  background: 'rgba(255,255,255,0.05)', border: `1px solid ${T.border}`,
                  color: T.text, fontSize: '13px', outline: 'none',
                  fontFamily: 'inherit', direction: pageDir as 'rtl' | 'ltr',
                }}
              />
              <button
                onClick={() => handleSend()}
                disabled={!chatInput.trim() || sendMessageMutation.isPending}
                style={{
                  padding: '10px 16px', borderRadius: '6px',
                  background: chatInput.trim() && !sendMessageMutation.isPending ? 'rgba(66,165,245,0.2)' : 'rgba(255,255,255,0.04)',
                  border: `1px solid ${chatInput.trim() && !sendMessageMutation.isPending ? T.borderAct : T.border}`,
                  color: chatInput.trim() && !sendMessageMutation.isPending ? T.blue : T.textMuted,
                  cursor: chatInput.trim() && !sendMessageMutation.isPending ? 'pointer' : 'not-allowed',
                  transition: 'all 0.2s',
                }}
              >
                {sendMessageMutation.isPending ? <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> : <Send size={16} />}
              </button>
            </div>
          </div>

          {/* ── KPI Stats ── */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '12px' }} className="lg:grid-cols-4">
            {[
              { label: isAr ? 'مساحة الرصد' : 'Monitoring Area', value: systemStats.totalMonitoredArea.toLocaleString(), unit: 'km²', color: T.blue },
              { label: isAr ? 'تنبيهات آخر 24 ساعة' : 'Alerts Last 24hr', value: systemStats.alertsLast24h, unit: isAr ? 'تنبيه' : 'Alert', color: T.red },
              { label: isAr ? 'بيانات معالجة' : 'Processed Data', value: systemStats.dataProcessed, unit: '', color: T.purple },
              { label: isAr ? 'متوسط وقت الاستجابة' : 'Average response time', value: systemStats.avgResponseTime, unit: '', color: T.amber },
            ].map(stat => (
              <div key={stat.label} style={{ padding: '14px 16px', borderRadius: '6px', background: T.card, border: `1px solid ${T.border}` }}>
                <div style={{ fontSize: '11px', color: T.textMuted, marginBottom: '6px' }}>{stat.label}</div>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: '4px' }}>
                  <span style={{ fontSize: '22px', fontWeight: 700, color: stat.color, fontFamily: T.fontMono }}>{stat.value}</span>
                  {stat.unit && <span style={{ fontSize: '11px', color: T.textMuted }}>{stat.unit}</span>}
                </div>
              </div>
            ))}
          </div>

          {/* ── Charts ── */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '16px' }}>
            <div style={{ padding: '16px', borderRadius: '8px', background: T.card, border: `1px solid ${T.border}` }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '14px' }}>
                <Calendar size={14} style={{ color: T.blue }} />
                <span style={{ fontSize: '13px', fontWeight: 600, color: T.text }}>{isAr ? 'الهطول — 14 يوماً' : 'Rainfall — 14 day'}</span>
              </div>
              <ResponsiveContainer width="100%" height={180}>
                <AreaChart data={rainfallData14}>
                  <defs>
                    <linearGradient id="rainGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor={T.blue} stopOpacity={0.3} />
                      <stop offset="95%" stopColor={T.blue} stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="time" tick={{ fontSize: 9, fill: T.textMuted }} />
                  <YAxis tick={{ fontSize: 9, fill: T.textMuted }} />
                  <Tooltip contentStyle={tooltipStyle} />
                  <ReferenceLine x={todayLabel} stroke={T.amber} strokeDasharray="4 2" strokeWidth={1.5} />
                  <Area type="monotone" dataKey="actual" stroke={T.blue} fill="url(#rainGrad)" strokeWidth={2} name="Actual" connectNulls={false} />
                  <Area type="monotone" dataKey="predicted" stroke={T.teal} fill="none" strokeWidth={1.5} strokeDasharray="4 2" name="Forecast" />
                </AreaChart>
              </ResponsiveContainer>
            </div>

            <div style={{ padding: '16px', borderRadius: '8px', background: T.card, border: `1px solid ${T.border}` }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '14px' }}>
                <TrendingUp size={14} style={{ color: T.red }} />
                <span style={{ fontSize: '13px', fontWeight: 600, color: T.text }}>{isAr ? 'مؤشر الخطر — 14 يوماً' : 'risk index — 14 day'}</span>
              </div>
              <ResponsiveContainer width="100%" height={180}>
                <LineChart data={riskTrend14}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="date" tick={{ fontSize: 9, fill: T.textMuted }} />
                  <YAxis domain={[0, 100]} tick={{ fontSize: 9, fill: T.textMuted }} />
                  <Tooltip contentStyle={tooltipStyle} />
                  <Legend wrapperStyle={{ fontSize: '10px' }} />
                  <ReferenceLine x={todayRiskLabel} stroke={T.amber} strokeDasharray="4 2" strokeWidth={1.5} />
                  <Line type="monotone" dataKey="abuDhabiCity" stroke={T.blue} strokeWidth={2} dot={false} name="Abu Dhabi" />
                  <Line type="monotone" dataKey="alAin" stroke={T.green} strokeWidth={2} dot={false} name="Al Ain" />
                  <Line type="monotone" dataKey="alDhafra" stroke={T.amber} strokeWidth={2} dot={false} name="Al Dhafra" />
                  <Line type="monotone" dataKey="alWathba" stroke={T.red} strokeWidth={2} dot={false} name="Al Wathba" />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* ── Regions risk bar chart ── */}
          <div style={{ padding: '16px', borderRadius: '8px', background: T.card, border: `1px solid ${T.border}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '14px' }}>
              <BarChart3 size={14} style={{ color: T.purple }} />
                <span style={{ fontSize: '13px', fontWeight: 600, color: T.text }}>{isAr ? 'مقارنة مؤشر الخطر — جميع المناطق' : 'Comparison risk index — all Regions'}</span>
            </div>
            <ResponsiveContainer width="100%" height={160}>
              <BarChart data={regions.map(r => ({ name: r.nameAr.split(' ')[0], risk: r.floodRisk, rainfall: r.rainfall }))} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" horizontal={false} />
                <XAxis type="number" domain={[0, 100]} tick={{ fontSize: 9, fill: T.textMuted }} />
                <YAxis type="category" dataKey="name" tick={{ fontSize: 10, fill: T.textMuted }} width={55} />
                <Tooltip contentStyle={tooltipStyle} formatter={(v: number) => [`${v}%`, 'risk index']} />
                <Bar dataKey="risk" fill={T.red} radius={[0, 3, 3, 0]} name="risk index" />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* ── Recent reports list ── */}
          <div style={{ padding: '16px', borderRadius: '8px', background: T.card, border: `1px solid ${T.border}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '14px' }}>
              <FileText size={14} style={{ color: T.teal }} />
                <span style={{ fontSize: '13px', fontWeight: 600, color: T.text }}>{isAr ? 'التقارير الأخيرة' : 'recent reports'}</span>
            </div>
            {[
              { name: 'Today\'s Incident Report', date: 'March 24, 2026', type: 'CSV', size: '48 KB' },
              { name: 'Analysis Data Satellites', date: 'March 23, 2026', type: 'JSON', size: '120 KB' },
              { name: 'Report Performance Models Artificial Intelligence', date: '22 March 2026', type: 'CSV', size: '65 KB' },
            ].map((r, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 0', borderBottom: i < 2 ? `1px solid ${T.border}` : 'none' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <FileText size={14} style={{ color: T.textMuted }} />
                  <div>
                    <div style={{ fontSize: '12px', color: T.text, fontWeight: 500 }}>{r.name}</div>
                    <div style={{ fontSize: '10px', color: T.textMuted }}>{r.date} · {r.size}</div>
                  </div>
                </div>
                <button
                  onClick={() => {
                    if (r.type === 'CSV') downloadCSV(`${r.name}.csv`, regions.map(reg => ({ 'Region': reg.nameAr, 'rainfall': reg.rainfall, 'Risk': reg.floodRisk })));
                    else downloadJSON(`${r.name}.json`, { report: r.name, regions, generatedAt: new Date().toISOString() });
                    toast.success(`downloaded ${r.name}`);
                  }}
                  style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '5px 12px', borderRadius: '4px', background: 'rgba(66,165,245,0.08)', border: `1px solid ${T.border}`, color: T.blue, fontSize: '11px', cursor: 'pointer' }}
                >
                  <Download size={11} /> {r.type}
                </button>
              </div>
            ))}
          </div>
        </>
      )}

      {/* CSS animations */}
      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @keyframes bounce { 0%, 80%, 100% { transform: translateY(0); } 40% { transform: translateY(-6px); } }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
        @keyframes stripPulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.6; } }
      `}</style>
    </div>
  );
}
